### ISSUE TITLE
Doesn't work on Centos 7 - glibc version request

### ISSUE THREAD

**Issue by aikaterna** [MinnDevelopment/udpqueue.rs#7]
Hi Minn, do you have any interest in supporting Centos 7/glibc 2.17? The OS has an end of life date of June 30, 2024 and I have Lavalink users that have that OS installed. The Lavalink error that comes up is a standard missing glibc version error, which is attached.
[spring.log](https://github.com/MinnDevelopment/udpqueue.rs/files/11243323/spring.log)

**Comment by MinnDevelopment** [comment]
I currently have no plans on supporting any older versions of GLIBC. To support this older version, I would have to change my entire setup to compile on Centos 7 as well, which I do not have any time to test and validate at this time.

**Comment by MinnDevelopment** [comment]
Closing, since CentOS 7 is now EOL.
