### ISSUE TITLE
musl - support

### ISSUE THREAD

**Issue by topi314** [MinnDevelopment/udpqueue.rs#8]
I'm currently looking into adding official support for musl into Lavalink/Lavaplayer. It would be nice to also have JDA-NAS working for that

This would include `x86-64` & `aarch64` like lavadsp already supports

**Comment by MinnDevelopment** [comment]
Lavaplayer currently doesn't offer a way to load libraries with different linking for the same platform. I'm unsure how I could support both musl and glibc.

**Comment by topi314** [comment]
lavadsps native loader has support for that. I'm currently preparing a pr for lavaplayer to use the same way

https://github.com/natanbc/native-loader/blob/master/src/main/java/com/github/natanbc/nativeloader/system/DefaultOperatingSystemTypes.java#L64

https://github.com/TopiSenpai/lavaplayer-fork/tree/musl-support
